blank_issues_enabled: false
contact_link:
  - name: EvilSquirrelGuy on GitHub
    url: https://www.github.com/EvilSquirrelGuy
    about: EvilSquirrelGuy's page on GitHub
  - name: OS Games Discord server
    url: https://discord.gg/yRNdUYy
    about: For more support, join the discord
  - OS Games on GitHub
    url: https://www.github.com/OS-Games-Official/
    about: OS Game's GitHub page with some useful info on it
